language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle/'

script: "./gradlew clean build"

# CI 실행 완료 시 메일 알람
notifications:
  email:
    recipients:
      - gkrwjaeoqkr1@gmail.com