language: java
jdk:
  - openjdk8 # java8이면, openjdk8

branches:
  only:
    - main # git default 브런치를 등록한다. (ex. master)

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - youngho110@naver.com

before_deploy:
  - zip -r baseballmate_deploy *
  - mkdir -p deploy
  - mv baseballmate_deploy.zip deploy/baseballmate_deploy.zip

deploy:
  # S3로 파일업로드
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repos settings에 설정된 값
    bucket: baseballmate-s3 # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true # master말고 다른 모든 브런치 허용